apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: wjn1/fibonacci-calculator-worker
      ports:
        - containerPort: 3000
